### ISSUE TITLE
Discuss technologies to use

### ISSUE THREAD

**Issue by KernelOverseer** [LprogrammersLm9awdin/TWIL-platform-back-end#2]
I am suggesting Using the MERN stack, but it's very open to discussion.

**Comment by AlaaZorkane** [comment]
If it's going to be content (articles etc) only then I suggest a CMS rather than building it from scratch - Something like https://strapi.io/

**Comment by EndlessBox** [comment]
@AlaaZorkane nic3ly said !

**Comment by ybenbrai** [comment]
am with the MERN proposition :)

**Comment by KernelOverseer** [comment]
i still don't know everything about what strapi does, I think we should come up b3da with a clear vision 3la platform, then see what we can do.

**Comment by MbarkErras** [comment]
I'd suggest using javascript with some library to handle ui like react and sticking to the basics, no fancy stuff so anyone can contribute.

**Comment by MbarkErras** [comment]
@KernelOverseer so basically I can't make a pull request to init the project until this issue about stack choice is resolved yak?

**Comment by KernelOverseer** [comment]
@MbarkErras basically yes, but i think let's go express and mongo for now.

**Comment by KernelOverseer** [comment]
@MbarkErras you can start setting things, front end is already taken care of

**Comment by MbarkErras** [comment]
not to be pain in the ass, but we need a way to manage who is doing what, saraha I don't want to do something that someone is already working nor someone doing something that I'm already on, I hope it's understandable

**Comment by KernelOverseer** [comment]
Do we agree that we'll use `typescript` ?

**Comment by AlaaZorkane** [comment]
I still think a custom server is a bad idea for now

**Comment by MbarkErras** [comment]
hey @AlaaZorkane, we don't have a short deadline, nor someone is paying us :)

**Comment by AlaaZorkane** [comment]
It's not about that, it's about choosing the right tools for the right job, my tech preferences are typegraphql postgresql you don't see me calling for that :v

**Comment by fdrissi** [comment]
we need to know first what kind of web application we are building, If we don't know what we are dealing with, we can't decide the right technology/tools to use.

**Comment by MbarkErras** [comment]
@AlaaZorkane it's no surprise that you've never built something interesting implementation wise, all you guys care about is putting fancy buzzwords all over, waiting for your tight opportunity to mention typescript, graphql, or some other shit.. it'd be better for me to sign off, as I can't stop myself from cringing every time.

**Comment by AlaaZorkane** [comment]
A little bit too personal buddy, it's just technologies no need to get angry about any of this, I guess that shows the lack of experience 😅

**Comment by KernelOverseer** [comment]
I kinda agree with @AlaaZorkane , getting things done, is the name of the game in web business.

**Comment by AlaaZorkane** [comment]
I also think that it's up to people who work in the field to discuss this (or atleast decide), trust me you won't see me debating implementations in the lib9wada/graphics (even in the context of web) etc... mostly because I know there are people here who are far more experienced in that than me, you can state your opinions that you've read in a blog or an article somewhere, but trust me it won't be as reliable as someone's who works in the field all day... anyhow to keep this short, I am in open mind about any of this, techs included, and I think everyone should be, you don't have to get angry, it doesn't have to get personal, and you certainly shouldn't feel attacked if I say typescript is better than javascript, dm me or even better, host an event and explain and state your case.

**Comment by MbarkErras** [comment]
[skipping the part where you establish a hierarchy of who can discuss what]
I think being personal is not looking at someone's statement and instead asking him for his resume before doing that (in case you didn't understand, like metaphorically 🤓)
stop claiming that I am angry or personal about this, you can pick any statement from what I said and give a counterexample instead and we'll be done with that, in less time, talking efficiency which is something js developers don't care about, like generally.
regarding the pull request of deleting my name, is just that I don't want to be affiliated with any kind of immature culty community, where people are just flexing names instead of facilitating stuff to get the work done.
as I believe that you are just smart enough to understand the following, you had claims about openness, openness is not recommending technologies where the very most people can't use to contribute back, again facilitating.
regarding hosting an event (wondering why you want someone to host an event just to talk to you, but yeah I love nerdy events), pick any day, here are my break times, 13:00, 16:15, 17:45 and 22:15 😉

**Comment by Stormix** [comment]
I know the discussion is closed, but I definitely agree with @AlaaZorkane , building something (most likely a CMS) from scratch is a pain in the ass, you'll be better off using some existing solution.
